version: 0.2
phases:
  install:
    runtime versions:
      nodejs: 12
  pre_build:
    commands:
      - npm build
      - npm install -g mocha
      - npm test
artifacts:
  files:
    - src/**/*
    git- package.json